export const FETCH_POSTS = "FETCH_POSTS";

export const FETCH_POST = "FETCH_POST";

export const FETCH_FRIENDSPOSTS = "FETCH_FRIENDSPOSTS";

export const UPDATE_NOTIFY_SOCKET = "UPDATE_NOTIFY_SOCKET";

export const UPDATE_SOCKET = "UPDATE_SOCKET";
